### PR TITLE
Support importing mods by dropping Zips or Folders (Continued with improved error handling)

### PR DESCRIPTION
**Pull request by outercloudstudio**
Continues #39 

# Changes
- Adds error handling and message if the import for some reason fails to work
- Adds errorType to app state to change error message when launching game vs importing mods

# Fixes
- Fixed importing zip mods breaking if recursive folders used

What it looks like when an error is thrown while importing a mod. Just threw a custom error called 'Cheese' for demonstration.
image

### CODE REVIEW

**Comment by OmniacDev** [comment]
the error pop ups look so bad lol, imma fix those

**Comment by OmniacDev** [comment]
Also quick note that we should really try to stop putting JS or TS code in the .tsx files. It's pretty bad practice and the builder doesn't really like it, so for any future additions, just create a new .ts file and export the functions from there to use in the .tsx files.

**Comment by FrederoxDev** [comment]
That's inconvenient lol. Why does it "not like it"? It works fine for the rest of the app xD

**Comment by OmniacDev** [comment]
Well if you look at how the web bundlers build the app, pretty much whenever you reload or something changes with the element, it is gonna call everything in that file again, even if it doesn't need to, which slows stuff down.

**Comment by OmniacDev** [comment]
that was a bad explanation but I think yk what I mean

**Comment by FrederoxDev** [comment]
> Well if you look at how the web bundlers build the app, pretty much whenever you reload or something changes with the element, it is gonna call everything in that file again, even if it doesn't need to, which slows stuff down.

If you're writing stuff in there it's typically state dependent code that should be being ran anyway no?

**Comment by OmniacDev** [comment]
a large majority of the stuff I can see in this commit should be in a .ts file, like the functions to import mods from zips. they aren't state dependant at all. Also the window listeners should 100% not be in there

**Comment by OmniacDev** [comment]
We already have a unzip function using jszip so using fflate is redundant

**Pull request merged**
