### PR TITLE
Update v3.0.0

### PR DESCRIPTION
**Pull request by OmniacDev**

### CODE REVIEW

**Comment by theaddonn** [comment]
so its 3.0.0 again lol

**Comment by OmniacDev** [comment]
@FrederoxDev could you review the changes again

**Comment by OmniacDev** [comment]
Ah you also mentioned in the other draft that the loading bar didn't "fit"? 
I'm assuming you meant the placement / style.

I do think having the loading bar always visible might be nicer, though I'm not sure exactly where to place it.
Any suggestions?

@FrederoxDev

**Comment by OmniacDev** [comment]
Status / Loading bar is now separate from the launcher page and is visible on every page. 
Screenshot 2024-08-10 194301
Screenshot 2024-08-10 194306
Screenshot 2024-08-10 194314
Screenshot 2024-08-10 194320
Screenshot 2024-08-10 194327

Not sure about the profile editor, looks a bit cluttered with the loading bar up top.

Screenshot 2024-08-10 194515

**Comment by OmniacDev** [comment]
Added a reinstall version button in the version manager 
Screenshot 2024-08-10 205527

**Comment by FrederoxDev** [comment]
By the loading bar didn't fit I meant it was wider than the window below it by a few pixels

**Comment by FrederoxDev** [comment]
I don't think up at the top is a good position for it, it's not the central focus, if anything maybe have it stay on the bottom

**Comment by FrederoxDev** [comment]
Always visible is nice though

**Comment by FrederoxDev** [comment]
We really need an add version button here: https://private-user-images.githubusercontent.com/64994204/356797218-a620cb59-f745-4e58-90a8-0eace72c0ba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTE2NDMsIm5iZiI6MTcyMzI5MTM0MywicGF0aCI6Ii82NDk5NDIwNC8zNTY3OTcyMTgtYTYyMGNiNTktZjc0NS00ZTU4LTkwYTgtMGVhY2U3MmMwYmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDEyMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNWJiZDMyMDQ0YTUwYTcwNWNmMDQyNjI3MDg5YWE1MGIzNmZhOWZiZDBlNDM1MTA3NzM1Nzc1MGI3N2Q2NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dARXC3UAfcpKSWnVwunBILfc1eNsHI0QgDVz7ckNRxY

**Comment by FrederoxDev** [comment]
Also just a suggestion, maybe when we're not on the main launcher page, we apply a glass effect (slight blur, for example) to make the background image less noisy and distracting from the other pages contents

**Comment by OmniacDev** [comment]
> We really need an add version button here: https://private-user-images.githubusercontent.com/64994204/356797218-a620cb59-f745-4e58-90a8-0eace72c0ba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyOTE2NDMsIm5iZiI6MTcyMzI5MTM0MywicGF0aCI6Ii82NDk5NDIwNC8zNTY3OTcyMTgtYTYyMGNiNTktZjc0NS00ZTU4LTkwYTgtMGVhY2U3MmMwYmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDEyMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNWJiZDMyMDQ0YTUwYTcwNWNmMDQyNjI3MDg5YWE1MGIzNmZhOWZiZDBlNDM1MTA3NzM1Nzc1MGI3N2Q2NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dARXC3UAfcpKSWnVwunBILfc1eNsHI0QgDVz7ckNRxY

this link doesnt work

**Comment by theaddonn** [comment]
No it doesn't work

**Comment by FrederoxDev** [comment]
Versions page

**Comment by OmniacDev** [comment]
wdym by add version though. the version gets installed / used when a profile is launched. Unless someone wanted to download the version files for something else, it wouldn't be very useful.

**Comment by FrederoxDev** [comment]
It should really be the other way around, versions are installed and managed on versions page. Profiles only then shows the versions

Plus for adding installs for other versions. As mentioned earlier in the thread, version paths shouldn't be in profiles either.

**Comment by OmniacDev** [comment]
nah that's unintuitive.

Imagine if you wanted two profiles with the same version, but installed in different locations.
With your proposal, you would have to go into the version manager, install the same version twice in those locations, and then somehow distinguish between two of the same versions, just with different paths, in the version select in the profiles.

Also, the profiles would then only be able to show already installed versions, which is the complete opposite of what it has been before, and what every other launcher does. 

The version manager was intended for tracking and being able to delete installed versions that were taking up space, not for installing new versions. 

the install directory option in the profile editor is entirely optional anyway, it just defaults to the `default_path` property in the `versions.json` file, so for most cases it won't be used.

**Comment by FrederoxDev** [comment]
Why is that unintuitive? Just change the label to be a list of installed versions. It's a lot nicer too since that gets rid of scrolling though a whole ass list of versions each time, especially when we get past 1.22 etc, 1.21 will be buried 

Also why would you want two installs of the same version xD? We don't care about supporting things like byte patching before, that would require different installs. We do everything at runtime. Profiles shouldn't need to care where the game is installed for this exact reason too.

Also a version manager not able to install versions is a tad silly lol.

**Comment by OmniacDev** [comment]
@FrederoxDev does this blur look good?

image

**Comment by FrederoxDev** [comment]
Lgtm

**Comment by OmniacDev** [comment]
https://github.com/user-attachments/assets/858f9d43-d255-4807-ae5b-76123c28984e

**Comment by OmniacDev** [comment]
Is there anything else that we need in this update?

**Comment by FrederoxDev** [comment]
If this is just the schema and some visuals update, that should be all after all of my feedback points have been put in

**Comment by FrederoxDev** [comment]
Talking of schemas, it would be nice to see the updated mod schemas

**Comment by OmniacDev** [comment]
> Talking of schemas, it would be nice to see the updated mod schemas

ah right, forgot about that. I'll do that tmrw

**Comment by OmniacDev** [comment]
#63

**Comment by OmniacDev** [comment]
Alright, that should be everything.

I'll mark this ready for review, if there's anything else needed then lmk.

**Comment by theaddonn** [comment]
is it everything, are you sure?
Do we have preview support? :3

**Comment by OmniacDev** [comment]
ffs

**Comment by OmniacDev** [comment]
You'll have to wait for the next update lol there's way too much in this one already

**Comment by FrederoxDev** [comment]
i'll take a look through later today

**Comment by FrederoxDev** [comment]
We're definitely not ready to merge just yet. a few things are:

- old mods don't show up at all, at minimum they should display errors
- there are still some pixel alignment issues and part of the UI looks jank because of this
- version paths are still in profiles, this needs to be moved

I'm gonna dive into it a little bit, so I potentially might end up doing it rn, unsure, will see.

**Comment by FrederoxDev** [comment]
I'm still not entirely happy with the profile editor page, i think the call to actions are a bit wrong, there is a giant delete profile button but now the button to exit is a tiny thing cowering in the corner

**Comment by OmniacDev** [comment]
> - old mods don't show up at all, at minimum they should display errors

I think for the mods they are fine not being showed. This is already a breaking update, and trying to display relatively detailed errors for the old mod config would need more schemas and validations which is pointless cause they're deprecated anyway. 

> - there are still some pixel alignment issues and part of the UI looks jank because of this

Could you send some SS of the alignment issues? It should've automatically set the zoom level to 0, so unless that isn't working then there's gotta be a different problem.

> - version paths are still in profiles, this needs to be moved

For the profile install path, I still think it should be per profile. The launcher already uses everything from the specified profile (mods, runtime, version) to start the game, and having moving the install path only further complicates the process of using a different path. There's honestly no reason why the profile shouldn't have it. It defaults to the version folder, so 99% of the time it won't ever be changed, and for the times when people do want a custom install directory, theres a bunch of issues with not having it per profile.

1. the first blaringly annoying issue would be that every time you changed the profile's version, you would also have to go into the version manager and install that version at the specific path that you wanted. This is just annoying and tedious if you wanted for example a "Latest Version" profile in a custom install directory. everytime the game updated, it wouldn't be as simple as just changing the version of the profile and just launching. you'd have to manually go through and add the new version, change it's install path, wait for it to install, and then change the profile's versionz and then finally launch.

2. as I said the launcher already uses the profile's install path to launch, etc. if it were to be on a version to version basis, then a bunch of stuff would need to be edited (for an arguably worser UX), and it would also be more complicated for no added benefit.

+ probably some more issues that my 1 am brain isn't remembering

**Comment by FrederoxDev** [comment]
rest of my feedback is in the discord btw

**Pull request closed without merging**
