### PR TITLE
Replace CRA with Vite

### PR DESCRIPTION
**Pull request by OmniacDev**
Replaces abandoned create-react-app bundler with **Vite**

### CODE REVIEW

**Comment by OmniacDev** [comment]
image

image

image

**Comment by OmniacDev** [comment]
GH Actions works

**Comment by OmniacDev** [comment]
@FrederoxDev this PR should be good to merge

**Comment by ZeroMemes** [comment]
Bro approved his own PR 🔥

**Comment by FrederoxDev** [comment]
Lol

I'll get around to this when I'm looking at the launcher next, there's not much priority for me until there's new features to push this in, and there's nothing planned for right now

**Comment by OmniacDev** [comment]
@ZeroMemes I'm just that good

**Comment by theaddonn** [comment]
This pr is gonna be left open for like the next 9 months, don't worry

**Comment by ATXLtheAxolotl** [comment]
That would never happen (and hypothetically if it did happen, it would not be me)

**Comment by OmniacDev** [comment]
wanna bet on it? >:)

**Comment by FrederoxDev** [comment]
LGTM

**Pull request merged**
