### PR TITLE
add(): Custom game directory support

### PR DESCRIPTION
**Pull request by ATXLtheAxolotl**
This PR will allow users to set a custom installation path for when Amethyst is downloading the game.

This PR has 2 uses:
- If for some reason you want to have your installation in a different location, it will be accessible easier.
- You can use existing launchers with it. For example, I prefer to use MCLauncher and I can simply use Amethyst-Launcher as an easy GUI installer for my MCLauncher versions.

### CODE REVIEW

**Comment by FrederoxDev** [comment]
Neat, could you provide some screenshots of the new UI, etc?

**Comment by ATXLtheAxolotl** [comment]
Default:
image

Path Selection:
image

Selected Path:
image

**Comment by FrederoxDev** [comment]
Good start, but I think it should be made a bit more clear that this is optional, maybe a checkbox could enable the visibility of this or something, or it be filled in with amethysts default path by default and rename it a more generic "Installation Directory"?

**Comment by theaddonn** [comment]
any progress on this?

**Comment by NTT1906** [comment]
> Good start, but I think it should be made a bit more clear that this is optional, maybe a checkbox could enable the visibility of this or something, or it be filled in with amethysts default path by default and rename it a more generic "Installation Directory"?

Instead, change "Custom directory" to "Install directory". If there are no changes, it will display the current installation folder, users just need to click to select the new folder.

**Comment by ATXLtheAxolotl** [comment]
> any progress on this?

Sorry I’ve forgotten to look at this, I’ll work on this later tonight.

**Comment by ATXLtheAxolotl** [comment]
@FrederoxDev, if you don't mind could you look over this again? I took NTT1906's advice to rename it and have it default to the default amethyst installation directory that way it is more clear to the user.

image

I also made an error show up if the path isn't valid
image

**Comment by FrederoxDev** [comment]
I think it might be interesting instead of this being per profile, instead having an option in settings called additional install directories, which we have read access to. That way other versions of the game can also be brung in

**Comment by FrederoxDev** [comment]
Than once an additional install directory is added, that version shows up in the versions list

**Comment by FrederoxDev** [comment]
IMO at some point, I think I will end up doing something similar to the mods page, which is more of a version manager, that way the list that is available in the profile maker, only includes versions that are installed

**Comment by ATXLtheAxolotl** [comment]
> I think it might be interesting instead of this being per profile, instead having an option in settings called additional install directories, which we have read access to. That way other versions of the game can also be brung in

What do you mean by custom versions? Do you mean custom .Appx ? If so I think we should make that an import button.

**Comment by OmniacDev** [comment]
This just changes where the version is installed right?

**Comment by FrederoxDev** [comment]
For now I'm going to close this PR, feel free to re-open it if progress is made

**Pull request closed without merging**
