### PR TITLE
Switch from using CRA to Vite

### PR DESCRIPTION
**Pull request by OmniacDev**
Replaced abandoned create-react-app bundler with Vite, 

Everything should be working, just double check in case I missed something.

### CODE REVIEW

**Comment by FrederoxDev** [comment]
Have you tested all the CI/CD scripts on a local branch?

also that artwork needs to be compressed, loading images is one of the things that was contributing to slow load times. Which is why I’ve limited the launcher to one art peice

**Comment by OmniacDev** [comment]
which scripts?

**Comment by FrederoxDev** [comment]
https://github.com/FrederoxDev/Amethyst-Launcher/blob/main/.github/workflows/build.yml

**Comment by OmniacDev** [comment]
ahh nope haven't tested those, I'll do it now

**Pull request closed without merging**
