### PR TITLE
Add a lot.

### PR DESCRIPTION
**Pull request by theaddonn**
I forgot what I all added in here.. a quick list of stuff that I remember:
- Mods are now reloaded ever X secs to show newly added mods
- Auto Updater added
- First steps for file handlers

### CODE REVIEW

**Comment by FrederoxDev** [comment]
The check for updates toggle should honestly just always be on. No need for it to be toggleable really

**Comment by theaddonn** [comment]
mhh I made it toggleable because some people might wanna not update and are annoyed by the popup appearing again and again

**Comment by theaddonn** [comment]
the bug you mentioned on discord should also now be fixed...

**Comment by FrederoxDev** [comment]
> mhh I made it toggleable because some people might wanna not update and are annoyed by the popup appearing again and again

I don't think there are any cases here where we want to allow people to stay on older versions, newer is always better here imo

**Comment by theaddonn** [comment]
I'll take that into consideration, another thing that is currently not working is the change of the mods directory.. I mixed some stuff up and it seems like the proxy is still using the old path

**Comment by FrederoxDev** [comment]
Also I gave it another try after the changes, it still seems to download it even if you suppress it. To recreate:

- release a ver with a bigger ver number
- open launcher, hit deny. Open console and it’ll log constantly that it is downloading
- after it downloads it will still prompt to setup again

We also should probably look into getting rid of it asking for an install directory each time

**Pull request merged**
