### PR TITLE
Draft 2.6.0

### PR DESCRIPTION
**Pull request by OmniacDev**

### CODE REVIEW

**Comment by FrederoxDev** [comment]
Immediate feedback:

image

There should be some content in these two panels saying no runtimes/mods, exactly like the profiles page

image

The launcher tries to import text when highlighting text in the text field lol

image

There definitely needs to be a better way to go back to the profiles screen from this menu, before it was the save button that had this purpose, but now it feels a bit awkward 

image

For the life of me i have no idea what this is, it looks like its trying to be a button, but its not pressable

image

We should keep the language as open mods folder, .shard is just the file extension for a mod

image

Versions page really needs a download version button, + my existing versions aren't showing up?

**Comment by FrederoxDev** [comment]
image

There is also some quite awkward/rough scaling happening here

**Comment by FrederoxDev** [comment]
image

Install directory should be handled in versions page, not the profile. the profile should have no care to where a version is installed

**Comment by FrederoxDev** [comment]
image

Some older issues i noticed not too long ago with the floating UI is that the loading bar no longer fits

**Comment by OmniacDev** [comment]
> image
> 
> There is also some quite awkward/rough scaling happening here

huh that is really strange, not sure what's causing that

**Comment by FrederoxDev** [comment]
> > image
> > There is also some quite awkward/rough scaling happening here
> 
> huh that is really strange, not sure what's causing that

fwiw, i still have scaling issues with the launcher

image

I cant change the zoom level at all

**Comment by OmniacDev** [comment]
> The launcher tries to import text when highlighting text in the text field lol

can't really fix that unfortunately, just the way drag & drop works in electron

**Comment by OmniacDev** [comment]
> > > image
> > > There is also some quite awkward/rough scaling happening here
> > 
> > 
> > huh that is really strange, not sure what's causing that
> 
> fwiw, i still have scaling issues with the launcher
> 
> image
> 
> I cant change the zoom level at all

yeah I thought it might be locked into a diff zoom level,

I'll see if I can force it to be normal on startup

**Comment by OmniacDev** [comment]
Hopefully that fixed the zoom issues

**Comment by OmniacDev** [comment]
> image
> 
> There should be some content in these two panels saying no runtimes/mods, exactly like the profiles page

Yeah, will do. Also for the versions and profiles pages

> image
> 
> There definitely needs to be a better way to go back to the profiles screen from this menu, before it was the save button that had this purpose, but now it feels a bit awkward

Since the profiles auto-save the save button isn't needed. I did add a close button in the top right, not sure how noticeable it is though.

> image
> 
> For the life of me i have no idea what this is, it looks like its trying to be a button, but its not pressable

It's supposed to be a "short" radial button, the "Mods" option shows up when the runtime isn't Vanilla. I might just hide the buttons entirely since there's no point showing a selected page if that's the only available one.

image

**Comment by OmniacDev** [comment]
Also, I'd suggest using 3.0.0 for the release version, since this is a pretty major update, and most of the old types aren't compatible

**Comment by theaddonn** [comment]
if you are add mod importing by clicking on `.amethyst` (or what ever extension flows ur boat) files... then I'll agree to calling it 3.0.0

**Comment by OmniacDev** [comment]
> if you are add mod importing by clicking on `.amethyst` (or what ever extension flows ur boat) files... then I'll agree to calling it 3.0.0

bruh

**Comment by OmniacDev** [comment]
All lists now show correct text when empty:
Screenshot 2024-08-07 220912
Screenshot 2024-08-07 221251

Profile editor navbar has been made clearer:
Screenshot 2024-08-07 220920
Screenshot 2024-08-07 220927

Changed button text to "Open folder" in shard manager:
Screenshot 2024-08-07 221135

**Comment by OmniacDev** [comment]
Probably need some different messages for when the lists are empty, right now it's mostly placeholder text.

**Comment by OmniacDev** [comment]
`.shard` files are now [supported](https://discord.com/channels/1184966397864980601/1184966399194570795/1270705160276152467)

**Comment by OmniacDev** [comment]
#62

**Pull request closed without merging**
